# Generated by Django 3.2.6 on 2021-11-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('alt_num', models.CharField(max_length=13)),
                ('BB_num', models.CharField(max_length=13)),
                ('Date_added', models.DateTimeField(blank=True)),
            ],
        ),
    ]
