# Generated by Django 3.2.6 on 2021-11-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='ID_num',
            field=models.CharField(default=0, max_length=13),
        ),
    ]
