# Generated by Django 3.2.6 on 2021-11-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_leads_id_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='Date_added',
        ),
    ]
