# Generated by Django 3.2.6 on 2021-11-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_remove_leads_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='ID_num',
            field=models.CharField(default=0, max_length=13, unique=True),
        ),
    ]
